DataFirstProject/Controllers/BSProductsController.cs
using DataFirstProject.Models.BikeStores;
using DataFirstProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DataFirstProject.Controllers
{
    //[Route("BikeStore/BSProducts")]
    //[Route("BikeStore/BSProducts/Index")]
    public class BSProductsController : Controller
    {
        private readonly BikeStoresContext _context;

        public BSProductsController(BikeStoresContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var vm = this.LoadData();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public IActionResult AddBrand(string brandName)
        {
            var vm = this.LoadData();
            if (ModelState.IsValid)
            {
                _context.Brands.Add(new Brand { BrandName = brandName });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public IActionResult AddCategory(string categoryName)
        {
            var vm = this.LoadData();
            if (ModelState.IsValid)
            {
                _context.Categories.Add(new Category { CategoryName = categoryName });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index", vm);
        }

        [NonAction]
        public BSCustomerProductVM LoadData()
        {
            var products = _context.Products.Include(x => x.Brand).Include(x => x.Category).ToList();
            BSCustomerProductVM vm = new()
            {
                Customers = _context.Customers.ToList(),
                Products = products,
            };
            return vm;
        }
    }
}

DataFirstProject/Views/BSProducts/Index.cshtml
@model BSCustomerProductVM

<div class="m-4">
    <ul class="nav nav-tabs" id="myTab">
        <li class="nav-item">
            <a href="#customers" class="nav-link active" data-bs-toggle="tab">Customers</a>
        </li>
        <li class="nav-item">
            <a href="#products" class="nav-link" data-bs-toggle="tab">Products</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="customers">
            <h4 class="mt-2">Customer Details</h4>
            <table class="table table-hover">
                <tr>
                    <th>Customer Id</th>
                    <th>First Name</th>
                    <th>Email</th>
                    <th>City</th>
                </tr>
                @foreach (var item in Model.Customers)
                {
                    <tr>
                        <td>@item.CustomerId</td>
                        <td>@item.FirstName</td>
                        <td>@item.Email</td>
                        <td>@item.City</td>
                    </tr>
                }
            </table>
        </div>
        <div class="tab-pane fade" id="products">
            <div class="row">
                <h4 class="mt-2">Product Details</h4>
                <div class="col-7">
                    <table class="table table-hover">
                        <tr>
                            <th>Product Name</th>
                            <th>Brand</th>
                            <th>Category</th>
                            <th>List Price</th>
                        </tr>
                        @foreach (var item in Model.Products)
                        {
                            <tr>
                                <td>@item.ProductName</td>
                                <td>@item.Brand.BrandName</td>
                                <td>@item.Category.CategoryName</td>
                                <td>@item.ListPrice</td>
                            </tr>
                        }
                    </table>
                </div>
                <div class="col-5">
                    <form method="post">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="nav-item">
                                <a href="#addbrand" class="nav-link active" data-bs-toggle="tab">Add Brand</a>
                            </li>
                            <li class="nav-item">
                                <a href="#addcategory" class="nav-link" data-bs-toggle="tab">Add Category</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="addbrand">
                                <h4 class="mt-2">Add New Brand</h4>

                                <div class="mb-3">
                                    <label for="BrandName" class="form-label">Brand Name</label>
                                    <input type="text" class="form-control" asp-for="BrandName" />
                                    <span asp-validation-for="BrandName"></span>
                                </div>
                                <div class="mt-2">
                                    <button type="submit" class="btn btn-outline-primary" asp-controller="BSProducts" asp-action="AddBrand">Add Brand</button>
                                </div>

                            </div>
                            <div class="tab-pane fade" id="addcategory">
                                <h4 class="mt-2">Add New Category</h4>
                                <div class="mb-3">
                                    <label for="CategoryName" class="form-label">Category Name</label>
                                    <input type="text" class="form-control" name="CategoryName" />
                                </div>
                                <div class="mt-2">
                                    <button type="submit" class="btn btn-outline-primary" asp-controller="BSProducts" asp-action="AddCategory">Add Category</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}